# Generated by Django 5.1.3 on 2024-12-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='draft',
            name='time_per_pick',
            field=models.IntegerField(default=60),
        ),
    ]
