# Generated by Django 5.1.3 on 2024-11-27 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rosteredplayer_pick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
