# Generated by Django 5.1.3 on 2024-11-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_draft_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draft',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
