# Generated by Django 5.1.3 on 2024-11-27 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_draft_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='draft',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='main.draft'),
        ),
    ]
