# Generated by Django 5.1.3 on 2024-12-10 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_team_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='draftplayer',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.team'),
        ),
    ]
